CI: Use os@endlessos.org as the addres for Flatpak External Data Checker
endlessm/endless-key-flatpak pull request #139
Opened 2023-12-11 10:13 UTC by starnight

Tried to make Flatpak External Data Checker's PR merged automatically before. But, it is failed and may due to the wrong mail address. Notice eos-google-chrome-app uses Flatpak External Data Checker and merges PRs automatically [1]. So, sync the mail address as os@endlessos.org with eos-google-chrome-app.

[1]: https://github.com/endlessm/eos-google-chrome-app/blob/4169d18cca057cfb88299c451a5a42da531b64a2/.github/workflows/check.yml#L18-L19

2023-12-11 10:24 UTC, wjt requested changes
This is not why flatpak-external-data-checker doesn't automatically merge these PRs.

On https://github.com/endlessm/eos-google-chrome-app/pull/181 the reason it gets merged automatically is:

https://github.com/endlessm/eos-google-chrome-app/blob/master/flathub.json

2023-12-11 10:24 UTC, wjt commented
Oh, I see that we have that, but not in the root of the repo.

Do you have the logs of it failing?

2023-12-11 10:26 UTC, wjt commented on .github/workflows/update.yaml
>            # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
This comment is no longer correct if you change the email address.

2023-12-11 10:29 UTC, wjt commented
The CI is failing which I think is more likely to be the reason the PRs don't get automerged.

2023-12-11 10:29 UTC, starnight commented on .github/workflows/update.yaml
>            # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
Oops!  Thanks!  Dropped the comment in the new commit.

2023-12-11 10:31 UTC, starnight commented
> Oh, I see that we have that, but not in the root of the repo.
> 
> Do you have the logs of it failing?

No corresponding failed log, actually.  The PRs just not merged automatically as result.  So, this is a guess.

2023-12-11 10:45 UTC, starnight commented
I believe the [`with open("flathub.json") as f:`](https://github.com/flathub/flatpak-external-data-checker/blob/6bef8ddc1efaceb7e029dcc3962e9c57fa5e6ca4/src/main.py#L293) means the `flathub.json` in the working directory, right?

2023-12-11 10:56 UTC, wjt commented
fedc does not automerge if there are failing CI checks.

> I believe the [`with open("flathub.json") as f:`](https://github.com/flathub/flatpak-external-data-checker/blob/6bef8ddc1efaceb7e029dcc3962e9c57fa5e6ca4/src/main.py#L293) means the `flathub.json` in the working directory, right?

It does, and the action for this repo does run in the right directory for that to work.

2023-12-11 10:59 UTC, starnight commented
Have to fix the appdata.xml checking failure.  So, I convert this to draft.

2023-12-11 18:05 UTC, dbnicholson commented
The problem we're having is that the CI isn't running at all. See https://github.com/endlessm/endless-key-flatpak/actions/workflows/build.yml. None of the runs were triggered by an fedc PR which all have names that begin with `Update`.

I could never figure out why, but my only idea was just to remove this email address and let it be whatever GitHub Actions sets the git author to. Using `os@endlessos.org` might work, though. On the other hand, `os@endlessos.org` does not represent any GitHub user that I'm aware of.

Also, eos-google-chrome-app is a little different. The CI runs in Jenkins, not GitHub Actions. In that case, Jenkins picks up the webhook event and starts the CI build. Then f-e-d-c can see that the CI was successful and can carry on with merging or not. We never get any builds triggered here, though.

2023-12-13 17:08 UTC, dbnicholson approved these changes
We can give it a shot and see what happens the next time an update is available.

2023-12-14 02:35 UTC, starnight commented
#142 is a good target!

2023-12-14 02:35 UTC, merged

2023-12-14 03:07 UTC, starnight commented
Or, maybe cause by this issue [GitHub Actions Not Run on PR Generated by GitHub Actions](https://github.com/orgs/community/discussions/25602)

2023-12-14 18:50 UTC, dbnicholson commented
> Or, maybe cause by this issue [GitHub Actions Not Run on PR Generated by GitHub Actions](https://github.com/orgs/community/discussions/25602)

Oh, good find! Following the links, that eventually points to https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs. I think we could use a personal access token from eos-shell-build for this purpose. I just did something like this recently... The drawbacks are another PAT to manage and the PRs will be created by the eos-shell-build user.

However, I kinda like https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens better.

2023-12-14 19:25 UTC, dbnicholson commented
This is basically exactly the same as https://phabricator.endlessm.com/T34806 where we needed a PAT to trigger a repository dispatch event because you can't trigger recursive workflows from the default `GITHUB_TOKEN`.

2023-12-14 19:30 UTC, dbnicholson commented
I just took the same token, which is scoped specifically for use in GitHub Actions with `repo` scope, and recorded it as a secret here with the name `WORKFLOW_TOKEN`. The idea being to use it when you need to trigger a recursive workflow. I'll add a commit to #142 that uses that token instead of `GITHUB_TOKEN`.

2023-12-14 19:45 UTC, dbnicholson commented
Well, that did trigger the checks, but it's not a fair test. In that case, the trigger was me pushing to the PR branch. The real test is when the trigger is the "Check for Updates" workflow. Anyway, the change to use the PAT is in #144.