metainfo: Use appstreamcli to validate, rather than appstream-util
endlessm/endless-key-flatpak pull request #33
Opened 2023-09-07 14:01 UTC by pwithnall

appstream-util comes from libappstream-glib, which is outdated and
unmaintained. appstreamcli is the more modern replacement, and it comes
from libappstream.

It implements more up to date validation rules, in particular it has
raised the maximum length of screenshot captions from 50 characters to a
more manageable 100 characters.

The downside is that it more strictly validates
`<compulsory_for_desktop>`, and rejects ‘endless’ because it’s not
officially registered as a desktop ID. Work around that for now by
temporarily removing that element from the XML during validation. In the
long term, we need to register the ID:
https://github.com/ximion/appstream/pull/522.

Signed-off-by: Philip Withnall <philip@tecnocode.co.uk>

2023-09-07 14:03 UTC, pwithnall commented
This should fix failures like this one: https://github.com/endlessm/endless-key-flatpak/actions/runs/6109528108/job/16580732377?pr=32

One outstanding question: before we standardise `endless` as a desktop ID forever, should we consider changing the capitalisation to `Endless` while we still can? It would be a bit disruptive in the OS, but easier to change now than after it’s standardised.

Confusingly, some software which uses the desktop ID (which pops up as `$XDG_CURRENT_DESKTOP`) does case-insensitive comparisons on it, but other software does case-sensitive ones. The consensus seems to be that it *is* case-sensitive.

2023-09-07 14:06 UTC, dbnicholson commented
Thanks. I just opened #34 to track this. I'll take a look at the upstream stuff.

2023-09-07 14:11 UTC, pwithnall commented
Looks like the CI flatpak build is actually building the `main` branch every time, not the branch from the PR. I’ll see if I can change that.

2023-09-07 14:31 UTC, dbnicholson commented on build-aux/flatpak/org.endlessos.Key.Devel.json
> +                    "url" : "https://github.com/endlessm/endless-key-flatpak.git"
I've had to mess with this in the past. I think you can just use a `file://` URL and then it "just works" since it's always using the current commit. Let me see if I can dig that up somewhere.

2023-09-07 14:37 UTC, dbnicholson commented on build-aux/flatpak/org.endlessos.Key.Devel.json
> +                    "url" : "https://github.com/endlessm/endless-key-flatpak.git"
Ah, it's specifying a `path` rather than a `url`. See [the Git sources docs](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html#idm46203909572144). The trick is the path to use. Hopefully a relative `../..` would work.

2023-09-07 14:40 UTC, pwithnall commented on build-aux/flatpak/org.endlessos.Key.Devel.json
> +                    "url" : "https://github.com/endlessm/endless-key-flatpak.git"
Thanks, I’ll try that. It turns out that my commit to use the default branch is complete lies, because I was confusing the default flatpak branch (which the flatpak is published on) with the default git branch (which is used to pull sources).

2023-09-07 14:43 UTC, dbnicholson commented on build-aux/flatpak/org.endlessos.Key.Devel.json
> +                    "url" : "https://github.com/endlessm/endless-key-flatpak.git"
I just tried this locally and it ends the same way with deciding to use `master`. The `path` is a nice speedup trick, but it doesn't do anything to help `flatpak-builder` decide what branch of the repo to use.

2023-09-07 14:45 UTC, dbnicholson commented on build-aux/flatpak/org.endlessos.Key.Devel.json
> +                    "url" : "https://github.com/endlessm/endless-key-flatpak.git"
Actually, maybe the thing to do is not use a `git` source at all. Instead a `dir` source with `path` set to `../..`. Let me try that.

2023-09-07 14:49 UTC, pwithnall commented
> Looking at the other examples, it certainly seems that like it should be capitalized. Hmm, that would be pretty disruptive to Endless OS. We could stage all the OS parts at once (although I don't know what all of them are), but what about Flatpaks? I was worried about [our external appstream](https://github.com/endlessm/gnome-software-data/blob/master/app-info/eos-extra.xml), but it doesn't use `<compulsory_for_desktop>`. The only case of that I've found is from the Kolibri flatpak.
> 
> You'd probably have to go spelunking to find all the places that the desktop ID is used. This [search](https://github.com/search?q=org%3Aendlessm%20xdg_current_desktop&type=code) is pretty enlightening, though.

Looking at those search results:
 * There don’t seem to be too many problem areas
 * A load of the old hardware reports suggest that at some point in the past it *was* capitalised as `Endless` anyway, so there could already be problems with this in the wild

I’m tempted to JFDI. I’d file a GitHub issue about it but I’m not really sure which project to file it under, given that the desktop is defined in our Debian packaging for gnome-session, which lives entirely in OBS. Should I use Phabricator once more?

2023-09-07 15:02 UTC, dbnicholson commented
> I’m tempted to JFDI. I’d file a GitHub issue about it but I’m not really sure which project to file it under, given that the desktop is defined in our Debian packaging for gnome-session, which lives entirely in OBS. Should I use Phabricator once more?

I think phabricator is the most appropriate for OS issues. It has all of our history and I'm pretty sure Will declared that Github was not for OS issues at the time the Github experiment was started.

The other thing you could do is just add `compulsory_for_desktop` with both the lower case and capitalized names. We'd probably need that in the Kolibri flatpak, too. Then we can work on the desktop ID in parallel.

2023-09-07 15:03 UTC, pwithnall commented on build-aux/flatpak/org.endlessos.Key.Devel.json
> +                    "url" : "https://github.com/endlessm/endless-key-flatpak.git"
I already updated it to use `dir` and the CI has passed and appears to be running on the right branch now. Could add `skip` as a separate PR?

2023-09-07 15:26 UTC, dbnicholson requested changes
Minor nitpick and then I think this is good to go!

2023-09-07 15:26 UTC, dbnicholson commented on build-aux/flatpak/org.endlessos.Key.Devel.json
> +                    "path" : "../.."
Can we skip a few things here? Mostly this will speed things up, but I think it also prevents some recursion.

```
"skip" : [
    ".git",
    ".flatpak-builder",
    "build",
    "flatpak_app",
    "repo"
]
```

The `.git` directory is obvious and I don't think any parts of the build currently try to inspect the git history. `.flatpak-builder` is where flatpak-builder caches everything. `build` is the typical meson build directory if you're doing this locally. `flatpak_app` and `repo` are where the [action](https://github.com/flatpak/flatpak-github-actions/blob/c14f6d4af8f66d453ff76be890a6127716606c13/flatpak-builder/index.js#L55) uses for the build and repo directories, respectively.

2023-09-07 15:44 UTC, pwithnall commented on build-aux/flatpak/org.endlessos.Key.Devel.json
> +                    "path" : "../.."
Done

2023-09-07 15:48 UTC, pwithnall commented
> > I’m tempted to JFDI. I’d file a GitHub issue about it but I’m not really sure which project to file it under, given that the desktop is defined in our Debian packaging for gnome-session, which lives entirely in OBS. Should I use Phabricator once more?
> 
> I think phabricator is the most appropriate for OS issues. It has all of our history and I'm pretty sure Will declared that Github was not for OS issues at the time the Github experiment was started.

I opened https://phabricator.endlessm.com/T34910, let’s continue discussion of this there.

2023-09-07 16:49 UTC, dbnicholson approved these changes

2023-09-07 16:49 UTC, merged

2023-10-30 16:28 UTC, wjt commented
Necro-commenting: Is Endless Key truly compulsory? I think that this flag, in effect, disables the "uninstall" action for the app in GNOME Software?

2023-10-30 16:33 UTC, dbnicholson commented
> Necro-commenting: Is Endless Key truly compulsory? I think that this flag, in effect, disables the "uninstall" action for the app in GNOME Software?

It is since `eos-kolibri-system-helper` is part of the OS and the way it works is to run the `org.endlessos.Key` flatpak from the host.

2023-10-30 16:47 UTC, wjt commented
Right, but that service gracefully gets disabled if the Flatpak is not present:

https://github.com/endlessm/eos-kolibri/blob/master/data/systemd/dbus-org.learningequality.Kolibri.Daemon.service.in#L3

2023-10-30 17:59 UTC, dbnicholson commented
Ah, true. @dylanmccall might know more of the history there.

2023-10-30 18:13 UTC, dylanmccall commented
Yep, it is completely safe and reasonable to uninstall the app. The only issue on Endless OS is people might be confused to find that Kolibri's _data_ persists (under `/var/lib/kolibri`). I think that's the reason why we did the `compulsory_for` bit in the first place. It isn't a good solution - a good solution involves a bunch of work in GNOME Software - but it's what we have.

We were doing the same at https://github.com/learningequality/kolibri-installer-gnome/blob/master/data/metainfo/org.learningequality.Kolibri.metainfo.xml.in.in#L206 for some reason, too, via this PR: https://github.com/learningequality/kolibri-installer-gnome/pull/63. Unfortunately there's no hint there of the context, but I think I'm remembering correctly here.

2023-10-30 18:46 UTC, wjt commented
On Mon, 30 Oct 2023, 6:13 pm Dylan McCall, ***@***.***> wrote:

> Yep, it is completely safe and reasonable to uninstall the app. The only
> issue on Endless OS is people might be confused to find that Kolibri's
> *data* persists (under /var/lib/kolibri). I think that's the reason why
> we did the compulsory_for bit in the first place. It isn't a good
> solution - a good solution involves a bunch of work in GNOME Software - but
> it's what we have.
>
Great point!