Add x-checker-data for kolibri-explore-plugin module
endlessm/endless-key-flatpak pull request #84
Opened 2023-09-22 11:19 UTC by starnight

Fixes: https://github.com/endlessm/endless-key-flatpak/issues/45

2023-09-22 22:56 UTC, dylanmccall commented
Thanks for taking care of this, @StarNight! I pushed a small change which uses the JSON checker against https://api.github.com/repos/endlessm/kolibri-explore-plugin/releases/latest to get the newest download files. That checker is documented over here: https://github.com/flathub/flatpak-external-data-checker#json-checker.

That works nicely for me, now, but I'm wondering what you all think about getting this to fetch the whl from github as well? We do have it there, and I feel like fetching the whl from pypi and everything else from gihub introduces the possibility of things getting out of sync.

2023-09-26 04:28 UTC, starnight commented
> It works nicely for me with that change, but I'm wondering what you all think about getting this to fetch the whl from github as well? We do have it there, and I feel like fetching the whl from pypi and everything else from github introduces the possibility of things getting out of sync.

Good question!  However, `kolibri_explore_plugin-7.1.0-py3-none-any.whl` includes the version string in the release page.  Besides, the wheel, apps-bundle and loading-screen are released in the same [release job](https://github.com/endlessm/kolibri-explore-plugin/blob/910e8b3e108ba8f7a3ed9e4a12cda557615ed1d2/.github/workflows/release.yml#L58).  It might be okay.

2023-09-26 10:34 UTC, starnight commented
Ok!  I found a way to deal the version string in `kolibri_explore_plugin-7.1.0-py3-none-any.whl`.  Updated the commit.

Besides, I also added `x-checker-data` into other modules, too.  But, skip **kolibri** module.  Because, Endless Key uses kolibri's pre-release right now.

2023-09-26 18:54 UTC, dbnicholson commented
> It works nicely for me with that change, but I'm wondering what you all think about getting this to fetch the whl from github as well? We do have it there, and I feel like fetching the whl from pypi and everything else from github introduces the possibility of things getting out of sync.

I've definitely thought about it a lot, but I think it's probably fine. Certainly they're the same file so long as no one is doing a manual upload to PyPI.

2023-09-26 18:56 UTC, dbnicholson commented
One thing I'd really like to see here is version constraints. Should they happen, we would not want to automatically upgrade to kolibri-explore-plugin 8.y or kolibri 0.17.z.

2023-09-26 19:20 UTC, dbnicholson requested changes
I'm certainly in agreement with using this, but I'm not as excited about blindly updating major versions of transitive dependencies.

2023-09-27 06:36 UTC, starnight commented on build-aux/flatpak/modules/iproute2.json
> +            }
I tested with iproute2 6.5.0.  Endless Key works as well.
Kolibri depends on [ifcfg](https://github.com/learningequality/kolibri/blob/v0.16.0-beta5/requirements/base.txt#L29) and the ifcfg package uses `ip` command from iproute2.

2023-09-27 07:12 UTC, starnight commented on build-aux/flatpak/modules/python3-kolibri-app-desktop-xdg-plugin.json
> +                "name": "Pillow"
Notice the restriction `Pillow>=8.2.0,<9.0.0` in [kolibri-app-desktop-xdg-plugin](https://github.com/endlessm/kolibri-app-desktop-xdg-plugin/blob/v1.1.4/setup.py#L28).

2023-09-27 08:27 UTC, starnight commented on build-aux/flatpak/modules/python3-virtualenv-api.json
> +                "name": "six",
I have tested without `modules/python3-virtualenv-api.json`.  Endless Key builds and works as usual.  I am going to drop `modules/python3-virtualenv-api.json`.  Please blame me if it is needed.

2023-09-27 10:47 UTC, starnight commented
Also, add `x-checker-data` into kolibri module.

2023-09-27 10:48 UTC, starnight commented on build-aux/flatpak/modules/python3-kolibri-app-desktop-xdg-plugin.json
> +                "name": "Pillow"
Updated the commit.

2023-09-27 17:15 UTC, dbnicholson approved these changes
This is good enough to start even though some of the version constraints won't work. I rebased to address the conflict and added the `v` stripping for the apps-bundle and loading-screen versions.

2023-09-27 17:15 UTC, dbnicholson commented on build-aux/flatpak/modules/python3-kolibri-explore-plugin.json
> +                "versions": {"<": "8.0.0"}
As it turns out, the JSON checker doesn't support `versions`, so we'll just have to do this with `jq` filters.

2023-09-27 19:00 UTC, merged

2023-09-28 02:59 UTC, starnight commented on build-aux/flatpak/modules/python3-kolibri.json
> +                "url-query": "first | .assets[] | select(.name==\"kolibri-\" + $version + \"-py2.py3-none-any.whl\") | .browser_download_url",
The `/latest` only shows the latest normal release.  But, we are using Kolibri's **pre-release**, which will not be shown by `/latest`.  So, we can only pick the first release by ourselves.